version: '3'

# Containers
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  rethinkdb:
    image: rethinkdb
    ports:
      - '28015:28015'
      - '28080:8080'

  ticker-server-ws:
    build: ./containers/ticker-server-ws
    volumes:
      - ./containers/ticker-server-ws/lib:/usr/src/app/lib
    links:
      - rethinkdb
    environment:
      RETHINKDB_HOST: rethinkdb
      RETHINKDB_PORT: 28015
      NODE_PORT: 80
    ports:
      - '8081:80'
    command: npm run dev

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/www:/var/www
    ports:
      - '8080:80'
    links:
      - ticker-server-ws
