version: '3'

services:

  # Server

  redis:
    build: ./containers/redis
    ports:
      - "6379:6379"

  couchdb:
    image: "apache/couchdb"
    ports:
      - "5984:5984"

  lenses:
    image: landoop/kafka-lenses-dev
    ports:
      - "3030:3030"
      - "9092:9092"
      - "2181:2181"
      - "8081:8081"
      - "9581:9581"
      - "9582:9582"
      - "9584:9584"
      - "9585:9585"
    environment:
      - ADV_HOST=192.168.0.103
      - SAMPLEDATA=0
      - DISABLE=azure-documentdb,coap,druid,ftp,hazelcast,hbase,influxdb,jms,kudu,rethink,voltdb,yahoo,hdfs,jdbc,twitter
    volumes:
      - ./containers/lenses/license.json:/license.json
    network_mode: host

  # Client

  web-client:
    build: ./containers/web-client
    volumes:
      - www-volume:/usr/src/dist

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - www-volume:/var/www
    ports:
      - "80:80"

volumes:
  www-volume: {}
