version: '3'

services:

  # Front

  dashboard:
    build: ./containers/dashboard
    volumes:
      - ./containers/dashboard/src:/usr/src/app/src
    ports:
      - '3000:3000'
    links:
      - nginx
    command: npm run dev


  # Reverse proxy

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/.htpasswd:/etc/nginx/.htpasswd
    links:
      - tickers
      - traders
      - records
      - wallets

  # API

  tickers:
    build: ./containers/ticker
    volumes:
      - ./containers/ticker/lib:/usr/src/app/lib
    links:
      - redis
    dns:
      - 192.168.0.1
      - 8.8.8.8
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      TICKER_SYMBOLS: 'btcusd,ethusd,neousd,xrpusd,bchusd,etcusd,ltcusd'
      TICKER_SLEEP: 6000
      DEBUG: 'alp:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev

  traders:
    build: ./containers/trader
    volumes:
      - ./containers/trader/lib:/usr/src/app/lib
    links:
      - redis
      - mongodb
      - records
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      NODE_PORT: 80
      DEBUG: 'alp:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev

  records:
    build: ./containers/record
    volumes:
      - ./containers/record/lib:/usr/src/app/lib
    links:
      - mongodb
    dns:
      - 192.168.0.1
      - 8.8.8.8
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      DEBUG: 'alp:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev

  wallets:
    build: ./containers/wallet
    volumes:
      - ./containers/wallet/lib:/usr/src/app/lib
    dns:
      - 192.168.0.1
      - 8.8.8.8
    environment:
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      DEBUG: 'alp:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev

  # Data

  mongodb:
    image: mongo:jessie
    ports:
      - '27017:27017'

  redis:
    build: ./containers/redis
    ports:
      - '6379:6379'
