version: '3'

# Containers
services:
  # rethinkdb:
  #   image: rethinkdb
  #   ports:
  #     - '28015:28015'
  #     - '28080:8080'
  #
  # ladder-server:
  #   build: ./containers/ladder-server
  #   volumes:
  #     - ./containers/ladder-server/lib:/usr/src/app/lib
  #   links:
  #     - rethinkdb
  #   environment:
  #     RETHINKDB_HOST: rethinkdb
  #     RETHINKDB_PORT: 28015
  #     NODE_PORT: 80
  #   command: npm run dev

  mongodb:
    image: mongo:jessie
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8080:80'
    links:
      - ticker-server

  ticker-server:
    build: ./containers/ticker-server
    volumes:
      - ./containers/ticker-server/lib:/usr/src/app/lib
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PREFIX: 'alpinist:'
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      DEBUG: 'alpinist:ticker:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev
