version: '3'

# Containers
services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  rethinkdb:
    image: rethinkdb
    ports:
      - '28015:28015'
      - '28080:8080'

  ticker-server:
    build: ./containers/ticker-server
    volumes:
      - ./containers/ticker-server/lib:/usr/src/app/lib
    links:
      - rethinkdb
    environment:
      RETHINKDB_HOST: rethinkdb
      RETHINKDB_PORT: 28015
      NODE_PORT: 80
      DEBUG: *
    command: npm run dev

  ladder-server:
    build: ./containers/ladder-server
    volumes:
      - ./containers/ladder-server/lib:/usr/src/app/lib
    links:
      - rethinkdb
    environment:
      RETHINKDB_HOST: rethinkdb
      RETHINKDB_PORT: 28015
      NODE_PORT: 80
    command: npm run dev

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8080:80'
    links:
      - ticker-server
      - ladder-server
