version: '3'

# Containers
services:
  mongodb:
    image: mongo:jessie
    ports:
      - '27017:27017'

  redis:
    build: ./containers/redis
    ports:
      - '6379:6379'

  nginx:
    restart: always
    build: ./containers/nginx
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - '8080:80'
    links:
      - tickers
      - traders

  tickers:
    build: ./containers/ticker
    volumes:
      - ./containers/ticker/lib:/usr/src/app/lib
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      TICKER_SYMBOLS: 'btcusd,ethusd,neousd'
      TICKER_SLEEP: 6000
      DEBUG: 'alp:ticker:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev

  traders:
    build: ./containers/trader
    volumes:
      - ./containers/trader/lib:/usr/src/app/lib
    links:
      - redis
      - mongodb
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      BITFINEX_KEY: 'GSzq5kVQY1rOvQoMb3ASADhgvX23JI6Q6x0JW2KTC6P'
      BITFINEX_SECRET: 'vLgU1HuVbxF10qhkHhaheKc1e1G3ccLEn0IWig089e2'
      NODE_PORT: 80
      DEBUG: 'alp:trader:*'
      DEBUG_COLORS: 'true'
      DEBUG_HIDE_DATE: 'false'
    command: npm run dev
